version: "2" # https://docs.docker.com/compose/compose-file/

services:

  apache:
    build:
     
      dockerfile: Dockerfile
      image: image: 'bitnami/apache:latest'
    restart: always
    ports:
      - "80:80"
