version: "2" # https://docs.docker.com/compose/compose-file/

services:

  nginx:
    build:
     
      dockerfile: ./docker-build/Dockerfile.nginx-proxy
    restart: always
    ports:
      - "80:80"
