FROM jwilder/nginx-proxy:latest 

RUN apt-get update \
        && apt-get install -y curl \
        && rm -rf /var/lib/apt/lists/*


RUN echo "daemon off;" >> /etc/nginx/nginx.conf \
 && sed -i 's/^http {/&\n    server_names_hash_bucket_size 128;/g' /etc/nginx/nginx.conf

